const sqlite3 = require('better-sqlite3');
const fs = require('fs');

const dbPath = process.env.HOME + '/Library/Application Support/amazon-ebay-tool/ebay_cache.db';
const db = new sqlite3(dbPath, { readonly: true });

const categories = ['75041', '179203', '180918', '180954', '75034', '161586', '176995'];
let allAspectsMap = new Map(); // aspectName -> usage

for (const cat of categories) {
  const rows = db.prepare('SELECT aspectName, usage FROM aspects WHERE categoryId = ?').all(cat);
  for (const row of rows) {
    const existingUsage = allAspectsMap.get(row.aspectName);
    
    // Usage precedence: REQUIRED > RECOMMENDED > OPTIONAL
    const getWeight = (usage) => {
      if (usage === 'REQUIRED') return 3;
      if (usage === 'RECOMMENDED') return 2;
      return 1;
    };
    
    if (!existingUsage || getWeight(row.usage) > getWeight(existingUsage)) {
      allAspectsMap.set(row.aspectName, row.usage);
    }
  }
}
db.close();

// Sort aspects similar to our tool: REQUIRED -> RECOMMENDED -> OPTIONAL, then alphabetical
const sortedAspects = Array.from(allAspectsMap.entries()).sort((a, b) => {
  const weightA = a[1] === 'REQUIRED' ? 3 : (a[1] === 'RECOMMENDED' ? 2 : 1);
  const weightB = b[1] === 'REQUIRED' ? 3 : (b[1] === 'RECOMMENDED' ? 2 : 1);
  if (weightA !== weightB) return weightB - weightA;
  return a[0].localeCompare(b[0]);
});

const generatedHeaders = sortedAspects.map(a => 'C:' + a[0]);

// Read master file headers
const masterPath = process.env.HOME + '/Downloads/Archives/File 7 Product/master_7cats_FILLED - master_7cats_FILLED.csv.csv';
const content = fs.readFileSync(masterPath, 'utf-8').split('\n');
let masterHeaders = [];
for (let i=0; i<10; i++) {
  if (content[i] && content[i].startsWith('*Action')) {
    masterHeaders = content[i].split(',').filter(h => h.startsWith('*C:') || h.startsWith('C:')).map(h => h.replace(/^\*?C:/, 'C:'));
    break;
  }
}

// Ensure both have the same elements regardless of order
const generatedSet = new Set(generatedHeaders);
const masterSet = new Set(masterHeaders);

const missingInGenerated = masterHeaders.filter(x => !generatedSet.has(x));
const extraInGenerated = generatedHeaders.filter(x => !masterSet.has(x));

console.log('--- TEST MERGING LOGIC ---');
console.log('Total aspects generated by Tool logic:', generatedHeaders.length);
console.log('Total aspects in Master CSV:', masterHeaders.length);

console.log('\nAspects in Master but Missing in Tool (should be 0):', missingInGenerated);
console.log('Extra Aspects in Tool not in Master:', extraInGenerated);

if (missingInGenerated.length === 0) {
  console.log('\n✅ SUCCESS: 100% Cột C: trong file master đều được Tool gộp đầy đủ!');
}

console.log('\n--- Danh sách cột do tool gen ra (Theo đúng thứ tự Tool sinh ra): ---');
console.log(generatedHeaders.join(', '));
